name: simcronomicon-env
channels:
  - conda-forge
  - defaults

dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.12.11
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - alabaster==1.0.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - autopep8==2.3.2
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.1
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.3.2
      - coverage==7.8.2
      - cycler==0.12.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - defusedxml==0.7.1
      - docstring-parser-fork==0.0.12
      - docutils==0.21.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fonttools==4.57.0
      - geopandas==1.0.1
      - h5py==3.13.0
      - idna==3.10
      - igraph==0.11.8
      - imagesize==1.4.1
      - iniconfig==2.1.0
      - ipykernel==6.29.5
      - ipython==9.2.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.8
      - lxml==5.4.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - narwhals==1.39.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nbsphinx==0.9.7
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numpy==2.2.5
      - osmnx==2.0.3
      - packaging==25.0
      - pandas==2.2.3
      - pandoc==2.4
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pillow==11.2.1
      - platformdirs==4.3.8
      - plotly==6.1.0
      - pluggy==1.5.0
      - plumbum==1.9.0
      - ply==3.11
      - prompt-toolkit==3.0.51
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pycodestyle==2.13.0
      - pydoclint==0.6.6
      - pygments==2.19.1
      - pyogrio==0.11.0
      - pypandoc==1.15
      - pyparsing==3.2.3
      - pyproj==3.7.1
      - pytest==8.3.5
      - pytest-cov==6.1.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==26.4.0
      - referencing==0.36.2
      - requests==2.32.3
      - roman-numerals-py==3.1.0
      - rpds-py==0.25.1
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - shapely==2.1.0
      - six==1.17.0
      - snowballstemmer==3.0.1
      - soupsieve==2.7
      - sphinx==8.1.3
      - sphinx-rtd-theme==3.0.2
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stack-data==0.6.3
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.14.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - wcwidth==0.2.13
      - webencodings==0.5.1