name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test_and_docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: simcronomicon-env
          environment-file: environment.yml

      - name: Install dev dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge pytest pytest-cov autopep8 sphinx sphinx-rtd-theme ghp-import
          pip install -e .
          
      # Run tests
      - name: Run tests with coverage
        shell: bash -l {0}
        run: |
          pytest --cov=.

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build HTML documentation
        if: matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/main' && github.event_name == 'push'
        shell: bash -l {0}
        run: |
          cd docs/
          make html

      - name: Deploy to GitHub Pages using ghp-import
        if: matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/main' && github.event_name == 'push'
        shell: bash -l {0}
        run: |
          ghp-import -n -p -f docs/build/html

      - name: Output documentation URL
        if: matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Documentation deployed to: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"